/**
 * themes.ts
 * Defines the available typography & color combinations (combos) for the platform.
 * Feel free to add or modify presets here!
 */

export type ComboKey =
  | 'cozy-moments'       | 'timeless-glow'     | 'sweet-celebration'
  | 'golden-warmth'      | 'garden-gift'        | 'blush-poetry'
  | 'velvet-dusk'        | 'amber-journal'      | 'morning-linen'
  | 'soft-terracotta'    | 'cloudberry'         | 'sage-ritual'
  | 'honey-oak'          | 'lavender-letter'    | 'desert-sun'
  | 'mint-nostalgia'     | 'rose-library'       | 'spice-market'
  | 'marigold-festival'  | 'nordic-cozy';

export interface ThemeColors {
  bgPage: string;
  bgCard: string;
  textOnPage: string;
  textOnCard: string;
  bgAccent: string;
  textOnAccent: string;
  accentMuted: string;
  accentGlow: string;
  accentHover: string;
  bgGlass: string;
  bgGlassHover: string;
  borderSubtle: string;
  borderMid: string;
  textMuted: string;
}

export interface ComboConfig {
  label: string;           // Human-readable theme name
  headingFont: string;     // Heading font CSS variable (configured in layout.tsx)
  bodyFont: string;        // Body font CSS variable (configured in layout.tsx)
  colors: ThemeColors;     // Specific colors for this combo
}

export const themeComboMatrix: Record<ComboKey, ComboConfig> = {
  // ─── Cozy & Warm ──────────────────────────────────────────────────────────
  'cozy-moments': {
    label: 'Cozy Moments',
    headingFont: '--font-quicksand',
    bodyFont: '--font-nunito',
    colors: {
      bgPage: '#fdfbf7',
          bgCard: '#f4efe6',
          textOnPage: '#1c1917',
          textOnCard: '#6b5a4b',
          bgAccent: '#d97706',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(217,119,6,0.10)',
          accentGlow: 'rgba(217,119,6,0.22)',
          accentHover: '#b45309',
          bgGlass: 'rgba(0,0,0,0.025)',
          bgGlassHover: 'rgba(0,0,0,0.045)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#8c7a6b',
    },
  },
  'golden-warmth': {
    label: 'Golden Warmth',
    headingFont: '--font-fraunces',
    bodyFont: '--font-nunito',
    colors: {
      bgPage: '#fefaf2',
          bgCard: '#f8f0dc',
          textOnPage: '#1c1917',
          textOnCard: '#6b5228',
          bgAccent: '#c97d1a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(201,125,26,0.10)',
          accentGlow: 'rgba(201,125,26,0.24)',
          accentHover: '#a05c0e',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a7a4a',
    },
  },
  'honey-oak': {
    label: 'Honey Oak',
    headingFont: '--font-josefin',
    bodyFont: '--font-worksans',
    colors: {
      bgPage: '#fefcf7',
          bgCard: '#f5edde',
          textOnPage: '#1c1917',
          textOnCard: '#644e28',
          bgAccent: '#8b5e1a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(139,94,26,0.10)',
          accentGlow: 'rgba(139,94,26,0.22)',
          accentHover: '#6a430e',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a7a50',
    },
  },
  'nordic-cozy': {
    label: 'Nordic Cozy',
    headingFont: '--font-publicsans',
    bodyFont: '--font-inter',
    colors: {
      bgPage: '#f8f9fb',
          bgCard: '#eef0f5',
          textOnPage: '#1c1917',
          textOnCard: '#475569',
          bgAccent: '#2563eb',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(37,99,235,0.10)',
          accentGlow: 'rgba(37,99,235,0.20)',
          accentHover: '#1d4ed8',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#6b7280',
    },
  },

  // ─── Elegant & Editorial ──────────────────────────────────────────────────
  'timeless-glow': {
    label: 'Timeless Glow',
    headingFont: '--font-playfair',
    bodyFont: '--font-inclusivesans',
    colors: {
      bgPage: '#fffef9',
          bgCard: '#f5f0e8',
          textOnPage: '#1c1917',
          textOnCard: '#5c4a30',
          bgAccent: '#7c3a78',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(124,58,120,0.10)',
          accentGlow: 'rgba(124,58,120,0.22)',
          accentHover: '#5a2a56',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.11)',
          textMuted: '#8a7060',
    },
  },
  'blush-poetry': {
    label: 'Blush Poetry',
    headingFont: '--font-cormorant',
    bodyFont: '--font-opensans',
    colors: {
      bgPage: '#fef9f8',
          bgCard: '#f9ece9',
          textOnPage: '#1c1917',
          textOnCard: '#7a5550',
          bgAccent: '#c2593f',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(194,89,63,0.10)',
          accentGlow: 'rgba(194,89,63,0.22)',
          accentHover: '#a3402a',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.03)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#9c7571',
    },
  },
  'velvet-dusk': {
    label: 'Velvet Dusk',
    headingFont: '--font-cinzel',
    bodyFont: '--font-montserrat',
    colors: {
      bgPage: '#1e1a18',
          bgCard: '#2a2420',
          textOnPage: '#fafaf9',
          textOnCard: '#b89f90',
          bgAccent: '#d4845a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(212,132,90,0.15)',
          accentGlow: 'rgba(212,132,90,0.30)',
          accentHover: '#bf6a3e',
          bgGlass: 'rgba(255,255,255,0.05)',
          bgGlassHover: 'rgba(255,255,255,0.08)',
          borderSubtle: 'rgba(255,255,255,0.08)',
          borderMid: 'rgba(255,255,255,0.14)',
          textMuted: '#8a7068',
    },
  },
  'amber-journal': {
    label: 'Amber Journal',
    headingFont: '--font-merriweather',
    bodyFont: '--font-sourcesans',
    colors: {
      bgPage: '#fdfaf5',
          bgCard: '#f5ede0',
          textOnPage: '#1c1917',
          textOnCard: '#6d5332',
          bgAccent: '#e08c1a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(224,140,26,0.10)',
          accentGlow: 'rgba(224,140,26,0.22)',
          accentHover: '#b86e0e',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a7a50',
    },
  },
  'rose-library': {
    label: 'Rose Library',
    headingFont: '--font-ptserif',
    bodyFont: '--font-chivo',
    colors: {
      bgPage: '#fdfaf9',
          bgCard: '#f8f0ee',
          textOnPage: '#1c1917',
          textOnCard: '#7a5050',
          bgAccent: '#9b2b4a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(155,43,74,0.10)',
          accentGlow: 'rgba(155,43,74,0.22)',
          accentHover: '#7a1e38',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.03)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#9a7272',
    },
  },

  // ─── Playful & Celebratory ───────────────────────────────────────────────
  'sweet-celebration': {
    label: 'Sweet Celebration',
    headingFont: '--font-fredoka',
    bodyFont: '--font-lato',
    colors: {
      bgPage: '#fffafb',
          bgCard: '#fdf0f3',
          textOnPage: '#1c1917',
          textOnCard: '#6e5d62',
          bgAccent: '#e05a7a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(224,90,122,0.10)',
          accentGlow: 'rgba(224,90,122,0.22)',
          accentHover: '#c0415e',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.035)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#8f7d82',
    },
  },
  'cloudberry': {
    label: 'Cloudberry',
    headingFont: '--font-comfortaa',
    bodyFont: '--font-rubik',
    colors: {
      bgPage: '#fffcfa',
          bgCard: '#fdf4f0',
          textOnPage: '#1c1917',
          textOnCard: '#7a4858',
          bgAccent: '#c94870',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(201,72,112,0.10)',
          accentGlow: 'rgba(201,72,112,0.22)',
          accentHover: '#a33258',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.03)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#9a7080',
    },
  },
  'mint-nostalgia': {
    label: 'Mint Nostalgia',
    headingFont: '--font-varela',
    bodyFont: '--font-notosans',
    colors: {
      bgPage: '#f6fdfb',
          bgCard: '#e6f5f0',
          textOnPage: '#1c1917',
          textOnCard: '#2e6050',
          bgAccent: '#0d7a5a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(13,122,90,0.10)',
          accentGlow: 'rgba(13,122,90,0.22)',
          accentHover: '#085e42',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.03)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#5a8a78',
    },
  },
  'spice-market': {
    label: 'Spice Market',
    headingFont: '--font-baloo',
    bodyFont: '--font-signika',
    colors: {
      bgPage: '#fefcf8',
          bgCard: '#f8f0e4',
          textOnPage: '#1c1917',
          textOnCard: '#6b4a28',
          bgAccent: '#c05c18',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(192,92,24,0.10)',
          accentGlow: 'rgba(192,92,24,0.24)',
          accentHover: '#9a4010',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a7050',
    },
  },
  'marigold-festival': {
    label: 'Marigold Festival',
    headingFont: '--font-sniglet',
    bodyFont: '--font-lato',
    colors: {
      bgPage: '#fffdf5',
          bgCard: '#fff5d6',
          textOnPage: '#1c1917',
          textOnCard: '#5c4800',
          bgAccent: '#d4900a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(212,144,10,0.12)',
          accentGlow: 'rgba(212,144,10,0.28)',
          accentHover: '#a86e00',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a8040',
    },
  },

  // ─── Earthy & Organic ─────────────────────────────────────────────────────
  'garden-gift': {
    label: 'Garden Gift',
    headingFont: '--font-dm-serif',
    bodyFont: '--font-cabin',
    colors: {
      bgPage: '#ffffff',
          bgCard: '#f3f6f2',
          textOnPage: '#1c1917',
          textOnCard: '#47614a',
          bgAccent: '#2e7d32',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(46,125,50,0.10)',
          accentGlow: 'rgba(46,125,50,0.20)',
          accentHover: '#1b5e20',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#6a8f6e',
    },
  },
  'morning-linen': {
    label: 'Morning Linen',
    headingFont: '--font-lora',
    bodyFont: '--font-inter',
    colors: {
      bgPage: '#faf9f7',
          bgCard: '#f0ece6',
          textOnPage: '#1c1917',
          textOnCard: '#5c574f',
          bgAccent: '#3d7b73',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(61,123,115,0.10)',
          accentGlow: 'rgba(61,123,115,0.22)',
          accentHover: '#2a5e58',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.11)',
          textMuted: '#8c8880',
    },
  },
  'soft-terracotta': {
    label: 'Soft Terracotta',
    headingFont: '--font-prata',
    bodyFont: '--font-hind',
    colors: {
      bgPage: '#fefaf7',
          bgCard: '#f5ede5',
          textOnPage: '#1c1917',
          textOnCard: '#7a4e3a',
          bgAccent: '#b54a2a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(181,74,42,0.10)',
          accentGlow: 'rgba(181,74,42,0.22)',
          accentHover: '#8f3518',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.11)',
          textMuted: '#9c7060',
    },
  },
  'sage-ritual': {
    label: 'Sage Ritual',
    headingFont: '--font-urbanist',
    bodyFont: '--font-mulish',
    colors: {
      bgPage: '#f8faf6',
          bgCard: '#ecf0e8',
          textOnPage: '#1c1917',
          textOnCard: '#445740',
          bgAccent: '#4a7c59',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(74,124,89,0.10)',
          accentGlow: 'rgba(74,124,89,0.22)',
          accentHover: '#306040',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.11)',
          textMuted: '#6a8a70',
    },
  },
  'lavender-letter': {
    label: 'Lavender Letter',
    headingFont: '--font-bodoni',
    bodyFont: '--font-arimo',
    colors: {
      bgPage: '#fdfaff',
          bgCard: '#f4edf8',
          textOnPage: '#1c1917',
          textOnCard: '#5c4870',
          bgAccent: '#7e4eaa',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(126,78,170,0.10)',
          accentGlow: 'rgba(126,78,170,0.22)',
          accentHover: '#5e3488',
          bgGlass: 'rgba(0,0,0,0.015)',
          bgGlassHover: 'rgba(0,0,0,0.03)',
          borderSubtle: 'rgba(0,0,0,0.05)',
          borderMid: 'rgba(0,0,0,0.10)',
          textMuted: '#8a70a0',
    },
  },
  'desert-sun': {
    label: 'Desert Sun',
    headingFont: '--font-jost',
    bodyFont: '--font-assistant',
    colors: {
      bgPage: '#fdfaf5',
          bgCard: '#f5ede0',
          textOnPage: '#1c1917',
          textOnCard: '#7a5030',
          bgAccent: '#c0401a',
          textOnAccent: '#ffffff',
          accentMuted: 'rgba(192,64,26,0.10)',
          accentGlow: 'rgba(192,64,26,0.24)',
          accentHover: '#982c0e',
          bgGlass: 'rgba(0,0,0,0.02)',
          bgGlassHover: 'rgba(0,0,0,0.04)',
          borderSubtle: 'rgba(0,0,0,0.06)',
          borderMid: 'rgba(0,0,0,0.12)',
          textMuted: '#9a7858',
    },
  },
};
